Server:
  Port: 5005
  RunMode: debug

Logger:
  FilePath: ../logs/logs.log
  Encoding: json
  Level: debug

Cors:
  AllowOrigins: "*"

Postgres:
  Host: postgres_container
  Port: 5432
  User: postgres
  Password: admin
  DbName: RideMarketDb
  SslMode: false

Redis:
  Host: redis_container
  Port: 6379
  Db: 0
  Password: password
  PoolSize: 10
  PoolTimeOut: 15
  ReadTimeOut: 5
  WriteTimeOut: 5
  DialTimeOut: 5
  IdleCheckFrequency: 500
Password:
  IncludeChars: true
  IncludeDigits: true
  MinLength: 6
  MaxLength: 64
  IncludeUpperCase: true
  IncludeLowerCase: true