Server:
  Port: 5005
  RunMode: debug

Logger:
  FilePath: ../logs/logs.log
  Encoding: json
  Level: debug

Cors:
  AllowOrigins: "*"

Postgres:
  Host: localhost
  Port: 5432
  User: postgres
  Password: admin
  DbName: car_sale_db
  SslMode: disable
  ConnMaxIdleTime: 10
  MaxOpenConns: 100
  ConnMaxLifetime: 30

Redis:
  Host: localhost
  Port: 6379
  Db: 0
  Password: password
  PoolSize: 10
  PoolTimeOut: 15
  ReadTimeOut: 5
  WriteTimeOut: 5
  DialTimeOut: 5
  IdleCheckFrequency: 500
Password:
  IncludeChars: true
  IncludeDigits: true
  MinLength: 6
  MaxLength: 64
  IncludeUpperCase: true
  IncludeLowerCase: true
Otp:
  ExpireTime: 120
  Digits: 6
  Limiter: 100